# RomanNumerals appveyor.yml script

branches:
  only:
    - master

version: '{branch}-{build}'
image: Visual Studio 2017

install:
#  - git submodule update --init --recursive

before_build:
  nuget restore

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

configuration: Release
platform: Any CPU

build:
  parallel: true
  publish_nuget: false
  publish_nuget_symbols: false
  verbosity: minimal
  project: RomanNumerals.sln

after_build:
  ps: NuGet pack RomanNumerals\RomanNumerals.nuspec -Verbosity detailed -NonInteractive -IncludeReferencedProjects -NonInteractive -Properties ConfigurationName=Release -Symbols

test:
  assemblies:
    - '**\*Test.exe'
    - '**\*Test.dll'

artifacts:
  - path: 'RomanNumerals\bin\$(configuration)\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: rEYnR9JThbc6x8DdCo1K8+fgsGKzjNKzTZsldXFLYMm/tFPC7JWWvuKpVTrDBd+g
  skip_symbols: false

after_test:
  ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
